version: '3'
services:
  ui:
    image: 'bluerentalcars-frontend:latest'
    build:
      context: ./bluerentalcars-frontend
    container_name: brc-frontend
    depends_on:
      - app
      - db
      
    ports:
      - "80:3000"
    environment: 
      - APP_URL=http://localhost:8080/car-rental/api/
    networks:
      - carrental-net
  app:
    image: 'bluerentalcars-backend:latest'
    build:
      context: ./bluerentalcars-backend
    container_name: brc-backend
    depends_on:
      - db
     
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/carrental
    networks:
      - carrental-net
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    environment:
      - POSTGRES_USER=techprodb_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=carrental

    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - carrental-net

volumes:
    db-data:
networks:
    carrental-net:
        driver: bridge