version: '3.8'
services:
  ui:
    image: "msukrualev/frontend:2023"
    deploy:
      replicas: 3
      update_config:
          parallelism: 2
          delay: 5s
          order: start-first
    depends_on:
      - app
      - db
    links: 
      - "app"  
    ports:
      - "80:3000"
    environment: 
      - APP_URL=http://18.208.221.175:8080/car-rental/api/
    networks:
      - carrental-net
  app:
    image: "${IMAGE_TAG_BE}"
    deploy:
      replicas: 3
      update_config:
          parallelism: 2
          delay: 5s
          order: start-first
    depends_on:
      - db
    links:
      - "db" 
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/carrental
    networks:
      - carrental-net
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    environment:
      - POSTGRES_USER=techprodb_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=carrental

    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - carrental-net

volumes:
    db-data:
networks:
    carrental-net:
        driver: overlay
