---
- name: Docker ve diğer bileşenlerin kurulumu
  hosts: all
  become: yes
  
  tasks:
    - name: Docker kurulumu
      apt:
        name: docker.io
        state: present
      become: yes
  
    - name: Docker-Compose kurulumu
      apt:
        name: docker-compose
        state: present
      become: yes
  
    - name: AWS CLI kurulumu
      apt:
        name: awscli
        state: present
      become: yes
  
    - name: Git kurulumu
      apt:
        name: git
        state: present
      become: yes
  
    - name: Docker Swarm Visualizer imajının indirilmesi
      docker_image:
        name: dockersamples/visualizer
        state: present
      become: yes
  
    - name: Docker Swarm Visualizer servisinin çalıştırılması
      docker_container:
        name: swarm_visualizer
        image: dockersamples/visualizer
        state: started
        ports:
          - "8080:8080"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        become: yes
