---
- name: EC2 örneklerini gruplama ve filtreleme
  hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: auto

  tasks:
    - name: EC2 kaynaklarının dinamik envanterini oluştur
      ec2_instance_facts:
        region: us-east-1
      register: ec2_facts

    - name: Dinamik envanter grubunu oluştur
      add_host:
        name: "{{ item.private_ip_address }}"
        groups: "{{ item.tags.Name }}"
      loop: "{{ ec2_facts.instances }}"

    - name: Grup bilgilerini görüntüle
      debug:
        var: groups
