version: '3'
services:
  ui:
    image: IMAGE_TAG_UI
    deploy:
      replicas: 1
    depends_on:
      - app
      - db
    ports:
      - "80:3000"
    labels:
      kompose.service.expose: "carrental.msukrualev.link"
      kompose.service.type: "nodeport"
    environment: 
      - APP_URL=http://carrental.msukrualev.link:8080/car-rental/api/

  app:
    image: IMAGE_TAG_API
    deploy:
      replicas: 1
    depends_on:
      - db
    ports:
      - "8080:8080"
    
    restart: "always"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/carrental

  
  grafana-server:
    image: IMAGE_TAG_GR
    ports:
    - 3000:3000
      

  
  prometheus-server:
    image: IMAGE_TAG_PR
    ports:
    - 9090:9090
    

  db:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    environment:
      - POSTGRES_USER=techprodb_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=carrental
    ports:
      - "5432:5432"