apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kompose.cmd: kompose convert
    kompose.service.expose: carrental.msukrualev.link
    kompose.service.type: nodeport
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  rules: 
    - host: carrental.msukrualev.link
      http:
        paths:
          - backend:
              service:
                name: ui
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: pro.msukrualev.link
      http:
        paths:
          - backend:
              service:
                name: prometheus-server
                port:
                  number: 9090
            path: /
            pathType: Prefix        
    - host: gra.msukrualev.link
      http:
        paths:
          - backend:
              service:
                name: grafana-server
                port:
                  number: 3000
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
